### ISSUE TITLE
test identicalness before deploying

### ISSUE THREAD

**Issue by myoung3** [singularityhub/github-ci#4]
If deploying an image to an existing tag, it would be nice if this workflow only deployed .sif files that are actually different from the currently hosted image.  That way the timestamp of a tag doesn't change, for example, when a readme change is pushed to main.  Any thoughts on how best to test identicalness?

**Comment by vsoch** [comment]
Hmm so I’m not sure this is the behavior that everyone would want. Also I’m not sure this is a problem? Currently the workflow only builds changed recipes, so if just the README changes there would not be any container build.

**Comment by myoung3** [comment]
oh interesting! I hadn't noticed the build was conditional on the .def file changing. I'll have to study that a bit more to understand how it works.
