### ISSUE TITLE
Typo in a link in README

### ISSUE THREAD

**Issue by darachm** [singularityhub/github-ci#5]
I believe there are some links in the README aimed at a URL containing 'workfolws'.
I think it should be 'workflows' ?

Thanks for writeup/template!

**Comment by vsoch** [comment]
Ack, this is why I shouldn't be writing docs late at night. Thanks for the catch! https://github.com/singularityhub/github-ci/commit/aa4130b1ee77b235af48d1ea755b6c6295894a59
