### ISSUE TITLE
github token not working

### ISSUE THREAD

**Issue by adelavega** [singularityhub/github-ci#6]
Thank for this awesome example. 

I've got this working on my project here: https://github.com/neuroscout/neuroscout-cli/pull/136
I set it up to build based on Docker Hub builds using the same meta-data.

One thing I noticed is that for some reason, using `{{ secrets.GITHUB_TOKEN }}` did not work for me. Instead, I had to create a personal token from my account, and add it to the repository secrets. 

If so, it may be worth updating the example.

**Comment by adelavega** [comment]
Actually looks like the docs were updated to say:

> To authenticate to the Container registry within a GitHub Actions workflow, use the GITHUB_TOKEN for the best security and experience. If your workflow is using a personal access token (PAT) to authenticate to ghcr.io, then we highly recommend you update your workflow to use the GITHUB_TOKEN.

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

Not sure why it didn't work for me then

**Comment by adelavega** [comment]
ah, actually I found this: https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio

Although their GUI guide is lacking, I found a place to add access to my repos' actions under the package's settings

**Comment by vsoch** [comment]
It should indeed work - I think there could be a few reasons it wouldn't:

1. you didn't enable users to have public/private access to packages in the org settings
2. your user doesn't have the correct permissions (everywhere I've used this successfully I have admin/owner)

If you can give me a more specific error message I could perhaps help - I'm going for my run now but will be back in about an hour!

**Comment by adelavega** [comment]
Sorry I updated my comments from under your feet but I think I found the problem.

It's very unintuitive but even though a package is linked with a repo, that doesn't mean the repo's actions are automatically authorized to push to that package.

**Comment by adelavega** [comment]
![image](https://user-images.githubusercontent.com/2774448/129621258-5135c3a4-872a-4a81-86ab-8584ae066a6b.png)

**Comment by vsoch** [comment]
Ah gotcha! Do you want to PR to update the docs here and clarify what you did so the next person doesn’t run into the same issue? It would be greatly appreciated.

**Comment by adelavega** [comment]
Sure! I'll know shortly that this fixes my issue. I can also confirm I did the two things you mentioned above and that wasn't enough.
