### ISSUE TITLE
public pulling

### ISSUE THREAD

**Issue by adelavega** [singularityhub/github-ci#8]
Another question:

Is public pulling without auth on the client possible?

When I try to pull the container associated with this repo I get this error:

```
FATAL:   While pulling image from oci registry: error fetching image to cache: failed to get checksum for oras://ghcr.io/singularityhub/github-ci:latest: while resolving reference: failed to authorize: failed to fetch oauth token: unexpected status: 403 Forbidden
```

If I login to to github using a PAK, it works.

**Comment by vsoch** [comment]
I think it might be backwards - if you are authenticated with credentials and the container doesn't require it, it won't work. I think we opened an issue about this: https://github.com/sylabs/singularity/issues/212

**Comment by adelavega** [comment]
Ah, I see. Maybe I didn't properly clear my token when trying. I'll keep on eye on that issue.

**Comment by vsoch** [comment]
Can you double check that it's public? I don't see it:

![image](https://user-images.githubusercontent.com/814322/129631918-ec753c85-c5b4-4242-a38e-31d5d357cb22.png)

**Comment by adelavega** [comment]
So 1) I think my issue was that due to a bug, I couldn't "logout", so that confused me: https://github.com/sylabs/singularity/issues/214

2) I do believe my package is currently `internal` and I'm not sure how to change it to public. It seems to have defaulted to `internal`.

**Comment by adelavega** [comment]
Okay, got it. You should be able to see it now.

I suppose as far as this example is concerned what might be relevant is to point out that packages should be public if that's the intention, and clarifying what it may default to (internal, in my case)

**Comment by vsoch** [comment]
Ah, so I think that might be an org setting. Under settings for the org there should be a packages menu, and under there you can select what level of access to give org members for packages (I think default is internal).

**Comment by vsoch** [comment]
And your analysis makes sense - I would post a note on both singularity issues to say "plus 1! This was an issue for me too!" so they are better looked at.

**Comment by adelavega** [comment]
I see. I have all 3 (public/private/internal) checked, so maybe that if internal is allowed it default to it when creating it. Or perhaps that differs based on whether the package is created by a `PAK` or `GITHUB_TOKEN` in a ci action.
